stages:
  - build

build:
  stage: build
  tags: [vagrant-darwin]
  variables:
    RT_CI_VAGRANT_BOX_NAME: rutoken/macos
    RT_CI_VAGRANT_BOX_VERSION: 1.6.1
    RT_CI_VAGRANT_BOX_CPUS: 2
    RT_CI_VAGRANT_BOX_MEMORY: 4096
  script:
    - |
      xcodebuild clean build -scheme rt-ui-components \
                             -destination generic/platform=iOS \
                             -scmProvider system

