stages:
  - analyse
  - build
  
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

build:
  stage: build
  tags: [vagrant-darwin]
  variables:
    RT_CI_VAGRANT_BOX_NAME: rutoken/macos
    RT_CI_VAGRANT_BOX_VERSION: 1.6.1
    RT_CI_VAGRANT_BOX_CPUS: 2
    RT_CI_VAGRANT_BOX_MEMORY: 4096
  script:
    - |
      xcodebuild clean build -scheme rt-ui-components \
                             -destination generic/platform=iOS \
                             -scmProvider system

include:
  - project: rutoken/dev/devops/checker/code-quality
    ref: latest
    file: /code-quality.yaml


code-quality:
  stage: analyse
  extends: .code-quality
